# -*- coding: utf-8 -*-
"""MQTT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oO5Nfu3RWzc4AQjsBc2xD2xgK_tZ-rC1
"""

pip install paho-mqtt

import time
import paho.mqtt.client as mqtt

# Callback Function on Connection with MQTT Server
def on_connect( client, userdata, flags, rc):
    print ("Connected with Code :" +str(rc))
    # Subscribe Topic from here
    client.subscribe("Retr0")

# Callback Function on Receiving the Subscribed Topic/Message
def on_message( client, userdata, msg):
    # print the message received from the subscribed topic
    print ( str(msg.payload) )
    if str(msg.payload)=="b'encrypt'":
     encrypt()

def encrypt():
  print("Your data is encrypted")

client = mqtt.Client()
client.on_connect = on_connect
client.on_message = on_message

client.connect("broker.hivemq.com", 1883, 60)
client.username_pw_set("admin", "hivemq")


client.loop_forever()

